version: "3.7"

services:

  saltcorn-app:
    image: saltcorn/saltcorn
    container_name: saltcorn
    depends_on:
      - saltcorn-db
    command: "serve"
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment:
      - SALTCORN_SESSION_SECRET=${SALTCORN_SECRET}
      - PGHOST=saltcorn-db
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
    
  saltcorn-db:
    image: postgres:13-alpine
    container_name: saltcorn-db
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_USER=${PGUSER} # initdb.sql script will only work for user "postgres"
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}

